### PR TITLE
fix chemplant not consuming catalyst

### LINKED ISSUE #6308: Chem. Plant catalyst usage
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
Server Eta

#
#### What did you try to do, and what did you expect to happen?
 I wanted to make purple rocket fuel in one chemical plant with 8 parallels, but the following problems arose.
 1. The orange metal catalyst breaks during any other recipe in which it should not be used.
 2. When the strength of the catalyst reaches 1/50, it remains in this state and does not collapse
completely. But at the same time, empty catalysts appear in the ME. In the morning I threw 8 orange catalysts, and now I have 500 empty catalysts.
 3. And everything would not be so bad, but when the strength of the catalyst is in the 1/50 state, the chemical plant stops working in 8 parallels, but only in 1, which is VERY bad.

#
#### What happened instead? (Attach screenshots if needed)
image
image
image

#
#### What do you suggest instead/what changes do you propose? 
 Make sure that the catalyst does not lose strength when a recipe occurs in which it is not used.
Destroy the catalyst completely in a 1/50 strength state so that the new catalyst replaces it. This will immediately fix the problem with 1 active parallel instead of 8.

### PR DESCRIPTION
**Pull request by bombcar**
fix GTNewHorizons/GT-New-Horizons-Modpack#6308

The catalyst was being set null but it wasn't being synced because updateSlots doesn't touch the Catalyst Hatch.

I couldn't figure out how to make it do that, so I iterate over the array (which will only ever have one item) and update the slots.

Considering this is the first line of Java I've ever written, it's probably horribly wrong. *but it works*

Also removed an errant duplication of code.

### CODE REVIEW

File: src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java [hunk 1]
```diff
@@ -120,7 +120,8 @@ public final void updateSlots() {
 			if (i <= getSlotID_LastInput()) {
 				fillStacksIntoFirstSlots();
 			}
-		}            
+		}
+		tryFillUsageSlots();
```
Comment (bombcar) [inline src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java]: Not happy about this, but it's `private` and it calls updateSlots() I think ... which is this. But it works, it correctly loads the next catalyst, and it does NOT load two or something like that.

File: src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java [hunk 2]
```diff
@@ -40,13 +40,6 @@ public GT_MetaTileEntity_Hatch_NbtConsumable(String aName, int aTier, int aInput
 		mAllowDuplicateUsageTypes = aAllowDuplicateTypes;
 	}
 
-	public GT_MetaTileEntity_Hatch_NbtConsumable(String aName, int aTier, int aInputSlots, String[] aDescription, boolean aAllowDuplicateTypes, ITexture[][][] aTextures) {
```
Comment (bombcar) [inline src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java:43]: this is literally duplicate of the function above

Comment (draknyte1) [reply src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java:43]: It’s a constructor. They wouldn’t be identical.

**Review by draknyte1 — CHANGES_REQUESTED** [review]
Removing constructors is bad.

File: src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/GregtechMTE_ChemicalPlant.java [hunk 3]
```diff
@@ -766,6 +766,7 @@ public boolean checkRecipeGeneric(
 		this.mOutputItems = tOutputItems;
 		this.mOutputFluids = tOutputFluids;
 		updateSlots();
+		for (GT_MetaTileEntity_Hatch_Catalysts h : mCatalystBuses) h.updateSlots();
```
Comment (draknyte1) [inline src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/GregtechMTE_ChemicalPlant.java]: Keep the formatting consistent. 
new line with {}.

**Comment by bombcar** [comment]
> Removing constructors is bad.

What's a constructor?

File: src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java (hunk 2 above)
Comment (bombcar) [reply src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java:43]: constructor good 
intelij bad

File: src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java (hunk 1 above)
Comment (Glease) [reply src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java]: Just turn tryFillUsageSlots into public. It won't hurt.

Comment (bombcar) [reply src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java]: ok I can do that

Comment (bombcar) [reply src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java]: Reverting because that didn't work .... the bug came back

Comment (bombcar) [reply src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/nbthandlers/GT_MetaTileEntity_Hatch_NbtConsumable.java]: wait maybe I have the dumb

**Comment by Dream-Master** [comment]
@draknyte1 is this ready for a merge ?

**Comment by Dream-Master** [comment]
bombcar — Today at 5:12 PM
it works for me and I've tested it preeeety extensively
I say merge it, alks' comment was resolved but I couldn't mark it as such

**Review by Dream-Master — APPROVED** [review]
