### PR TITLE
Fix steam macerator generating byproducts And use new API from GT5u

### LINKED ISSUE #14028: Steam Grinder (steam tier macerator multiblock) broken since 2.3.5
### Your GTNH Discord Username

MakinToge

### Your Pack Version

2.3.5

### Your Server

zeta

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Hello,
I had a working steam grinder in 2.3.4 with no void option
I expect it to work in 2.3.5 too

### The Reality

It's impossible to turn on if not set as void item, it says "Not enough output space"
Also, now it give all maceration byproducts

### Your Proposal

to fix it, not being able to have the no void option is kind of risky without good logistic which you don't have at steam tier.
Also, having a steam tier multiblock giving byproducts bypass the needs of HV+ macerator to get them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by BlueWeabo**
Requires https://github.com/GTNewHorizons/GT5-Unofficial/pull/2185
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14028

Also uses new API from the GT5u PR.

### CODE REVIEW

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java [hunk 1]
```diff
@@ -123,4 +129,24 @@ public GT_Recipe.GT_Recipe_Map getRecipeMap() {
...
+
+            @Override
+            @Nonnull
+            public GT_ParallelHelper createParallelHelper(@Nonnull GT_Recipe recipe) {
+                return super.createParallelHelper(recipe).setCustomItemOutputCalculation(parallel -> {
+                    ArrayList<ItemStack> items = new ArrayList<>();
+                    ItemStack output = recipe.getOutput(0);
+                    if (output != null) {
+                        output = output.copy();
+                        output.stackSize *= parallel;
```
Comment (minecraft7771) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java:144]: Can this handle e.g. macerating iron block? (It would output 8*9=72 dust)

Comment (BlueWeabo) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java:144]: yes. I iron block only has 1 output. This won't handle machines being macerated tho.

Comment (minecraft7771) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java:144]: What I mean is that the stacksize of output would reach 72 dusts. Will the machine be able to actually output 72 dusts as 64 + 8 or will it cut off the 8 or another issue?

Comment (BlueWeabo) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java:144]: It will be able to output it.

**Review by minecraft7771 — APPROVED** [review]

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java (hunk 1 above)
Comment (BlueWeabo) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java:144]: After all. the originalStacksize*parallel was used before to lower chance rolling, but was now changed to not do that.

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java [hunk 2]
```diff
@@ -123,4 +129,24 @@ public GT_Recipe.GT_Recipe_Map getRecipeMap() {
...
+    @Override
+    protected ProcessingLogic createProcessingLogic() {
+        return new ProcessingLogic() {
+
+            @Override
+            @Nonnull
+            public GT_ParallelHelper createParallelHelper(@Nonnull GT_Recipe recipe) {
+                return super.createParallelHelper(recipe).setCustomItemOutputCalculation(parallel -> {
+                    ArrayList<ItemStack> items = new ArrayList<>();
+                    ItemStack output = recipe.getOutput(0);
```
Comment (miozune) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java:141]: I'm not sure if there's actually such a case, but this doesn't consider output chance for first output

**Comment by Dream-Master** [comment]
@BlueWeabo @minecraft7771

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java (hunk 2 above)
Comment (BlueWeabo) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMacerator.java:141]: forgot that is a possibility oops. will fix in a bit
