### PR TITLE
Fixes

### LINKED ISSUE #197: Zhuhai runs extremely slow, has a misleading NEI tooltip [1.7.20.GTNH]
## Expected Behavior
 The fishing port, when constructed according to the tooltip, should output items at a steady pace

## Current Behavior 
image
image

## Possible Solution
After comparing a working setup from an external source, these are my recommendations.
1. The tooltip should read an "open top" machine, rather than a "hollow" machine (this is the term used for everything with a closed top, including GT's EBF and GT++'s alloy blast smelter)
2. The tooltip or NEI recipe page should indicate a water input requirement.
3. The machine should not run without water (particularly not for ~70000 ticks)
4. If these can not be corrected in GT++ itself, include this info in the corresponding questbook page in GTNH.

## Steps to Reproduce (for bugs)
 1. Build a hollow Zhuhai with a closed top
 2. Add input/output bus, maintenance hatch, UHV muffler and ZPM energy hatch
 3. Supply appropriate power and activate

## Context
 I tried building this multiblock based off the in-game description, and noticed it showed extremely odd behaviour.

## Game Environment
 Current GTNH/Official server "Delta". I do not have the exact specs to this machine

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player? (not yet tested)
 - [x]    Multi Player?

### LINKED ISSUE #9546: Items disappear when IsaMill Controller is open
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.2

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

Open IsaMill Controller and click on an item in inventory

### The Reality

Items disappear

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #10075: Flotation Cell Regulator locked to invalid value
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.1.2.3qf with some jenkins jar

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Built Flotation Cell Regulator, but did not use immediately.

### The Reality

It is locked to {mLockedOreType: 0} when unloading chunk, not -1.
So it can process no ore.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #10076: Flotation Cell Regulator can process single stack of milled ore
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.1.2.3qf with some jenkins jar

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Flotation Cell Regulator needs 256 milled ore (and 32 Sodium/Potassium Ethyl Xanthate Dust) to work.

### The Reality

It can work with only 64 milled ore (and Xanthate), and produce full 1000L Froth.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by miozune**
- IsaMill
  - Fix IsaMill controller GUI void items
    - Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9546
  - Add structure check for Milling Ball Housing
    - Prevent oversight like https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9548
- Flotation Cell
  - Fix ore type can be locked to 0
    - Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10075
  - Add scan result for locked ore type
  - Fix height in tooltip
- Zhuhai
  - Don't consume energy to fill water
    - Same as Washing Plant
    - Close https://github.com/GTNewHorizons/GTplusplus/issues/197, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10423
  - Fix flowing water is not filled sometimes
  - Add info about filling water
- Washing Plant
  - Add info about filling water
- Algae Farm
  - Fix flowing water is not filled sometimes
- Others
  - Delegate to native isRecipeInputEqual
    - Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10076
  - Fix internal crash that was handled somewhere else

### CODE REVIEW

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntity_IndustrialFishingPond.java [hunk 1]
```diff
@@ -294,8 +301,8 @@ public boolean checkForWater() {
 			for (int j = mOffsetZ_Lower + 1; j <= mOffsetZ_Upper - 1; ++j) {
 				for (int h = 0; h < 2; h++) {
 					Block tBlock = aBaseMetaTileEntity.getBlockOffset(xDir + i, h, zDir + j);
-					// byte tMeta = aBaseMetaTileEntity.getMetaIDOffset(xDir + i, h, zDir + j);
-					if (tBlock == Blocks.air || tBlock == Blocks.flowing_water || tBlock == BlocksItems.getFluidBlock(InternalName.fluidDistilledWater)) {
+					byte tMeta = aBaseMetaTileEntity.getMetaIDOffset(xDir + i, h, zDir + j);
+					if (isNotStaticWater(tBlock, tMeta)) {
```
Comment (GlodBlock) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntity_IndustrialFishingPond.java:305]: do ore washer and algae farmer's water check need this fix?

Comment (miozune) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntity_IndustrialFishingPond.java:305]: I think yes, but this way of fix didn't work for distilled water in washer.
I didn't know about Algae, let me see

Comment (miozune) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntity_IndustrialFishingPond.java:305]: fixed for Algae

**Review by GlodBlock — APPROVED** [review]
