### PR TITLE
fixes XL bug to produce plasma and adds Steelux turbine change

### LINKED ISSUE #11368: XL Plasma Turbines in Fast mode produce plasma
### Your GTNH Discord Username

BlueWeabo#7517

### Your Pack Version

2.2.0.0-RC-2

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

XL Plasma turbine on fast mode produces 3x power and consumes 3x plasma

### The Reality

XL Plasma turbine on fast mode generates plasma
XLBug

### Your Proposal

Fix it I guess. (I will do it later, just need to get onto it)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #11378: XL Gas Turbine use incorrect calculation for some turbines
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Use huge ichorium turbines on XL gas turbine, input refinery gas (160 EU/L).

Huge ichorium turbine has 245% efficiency, overflow efficiency tier 3 and 470,400 EU/t output from optimal gas flow.

Ichorium turbine

XL gas turbine is equal to 16x gas turbine, so optimal gas flow for refinery gas should be 19,200 L/t, with 7,526,400 EU/t output.

### The Reality

The optimal gas flow I scan is 640L/t, with 250880 EU/t output.

refinerygas1

Ichorium's output changed from 2.1.2.4-18pre to 2.1.2.4-29pre (I can't remember the exact version), so I tried huge extremely unstable naquadah turbine, its output did not change in these versions. Its output is 168,750 EU/t with 245% efficiency. In XL gas turbine the output was 2,700,000 EU/t with optimal gas flow, the value is correct.. 

It seems that XL gas turbine is still using old output calculation.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by BlueWeabo**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11378

fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11368

### CODE REVIEW

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_Gas.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ int fluidIntoPower(ArrayList<FluidStack> aFluids, int aOptFlow, int aBaseEff) {
                 return GT_Utility.safeInt((long) aOptFlow * (long) aBaseEff / 10000L);
             }
 
-            actualOptimalFlow = GT_Utility.safeInt((long) aOptFlow / fuelValue);
+            actualOptimalFlow = GT_Utility.safeInt((long) (aOptFlow * flowMultipliers[1] / fuelValue));
```
Comment (eigenraven) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_Gas.java]: cast the flow multiplier into a double to avoid significant precision loss here

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_Plasma.java [hunk 2]
```diff
@@ -62,7 +63,7 @@ public int getFuelValue(FluidStack aLiquid) {
         return 0;
     }
 
-    @Override
+    /*@Override
```
Comment (eigenraven) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_Plasma.java]: remove instead of commenting

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_SHSteam.java [hunk 3]
```diff
@@ -80,7 +80,7 @@ int fluidIntoPower(ArrayList<FluidStack> aFluids, int aOptFlow, int aBaseEff) {
         int remainingFlow = MathUtils.safeInt((long) (aOptFlow
                 * 1.25f)); // Allowed to use up to 125% of optimal flow.  Variable required outside of loop for
         // multi-hatch scenarios.
-        this.realOptFlow = aOptFlow;
+        this.realOptFlow = aOptFlow * flowMultipliers[0];
```
Comment (eigenraven) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_SHSteam.java]: also use doubles here

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_Steam.java [hunk 4]
```diff
@@ -88,7 +88,7 @@ int fluidIntoPower(ArrayList<FluidStack> aFluids, int aOptFlow, int aBaseEff) {
         int remainingFlow = MathUtils.safeInt((long) (aOptFlow
                 * 1.25f)); // Allowed to use up to 125% of optimal flow.  Variable required outside of loop for
         // multi-hatch scenarios.
-        this.realOptFlow = aOptFlow;
+        this.realOptFlow = aOptFlow * flowMultipliers[0];
```
Comment (eigenraven) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GT_MTE_LargeTurbine_Steam.java]: double

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GregtechMetaTileEntity_LargerTurbineBase.java [hunk 5]
```diff
@@ -475,9 +477,14 @@ public boolean checkRecipeGeneric(
                                                 .getSpeedMultiplier()
                                         * GT_MetaGenerated_Tool.getPrimaryMaterial(aStack).mToolSpeed
                                         * 50));
+                        if (aTotalOptimalFlow<0)
+                            GTNHLib.proxy.addDebugToChat(String.valueOf(aTotalOptimalFlow) + "Base Turbine");
```
Comment (eigenraven) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/turbines/GregtechMetaTileEntity_LargerTurbineBase.java]: if it underflows, set it to some sensible value like 1 alongside debug output

**Review by eigenraven — APPROVED** [review]
