### PR TITLE
ExxonMobile Chemical Plant: Fix the Blockrenderer Structure Preview 

### LINKED ISSUE #13060: BlockRenderer shows way too many Catalyst Housings for Chem Plant
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

it should show the current structure. Which has at most one catalyst housing.

### The Reality

image

### Your Proposal

fix it. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Fiyorin**
this makes it suggest to use only 1 Catalyst Housing in the structure preview.

image

(the multi can still form with 0 or multiple housings.
recipes that require catalysts only work with 1 housing.)

fixes [#13060](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13060)

### CODE REVIEW

**Comment by Dream-Master** [comment]
How many needs it at minimum. Only one?

**Comment by Fiyorin** [comment]
> How many needs it at minimum. Only one?

at minimum none at all
often with 1 if the recipe uses a catalyst

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/GregtechMTE_ChemicalPlant.java [hunk 1]
```diff
@@ -1,8 +1,6 @@
 package gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.chemplant;
 
-import static com.gtnewhorizon.structurelib.structure.StructureUtility.ofChain;
-import static com.gtnewhorizon.structurelib.structure.StructureUtility.transpose;
-import static com.gtnewhorizon.structurelib.structure.StructureUtility.withChannel;
+import static com.gtnewhorizon.structurelib.structure.StructureUtility.*;
```
Comment (minecraft7771) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/GregtechMTE_ChemicalPlant.java]: Don't do wildcard import.

**Review by minecraft7771 — CHANGES_REQUESTED** [review]

**Review by minecraft7771 — APPROVED** [review]
