### PR TITLE
Fixes for overflow valve, wireless charger, and transmission components recipes and ids

### LINKED ISSUE #15045: Overflow Valve (LV) is missing a recipe
### Your GTNH Discord Username

vovassgreat

### Your Pack Version

nightly 248

### Your Server

unrelated

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Should be craftable, as it there is quest for it.

### The Reality

Has no recipe (other overflow valves are still craftable though).

### Your Proposal

Either add a recipe or remove the quest.

This issue was made on behalf of EvgenWarGold.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by chochem**
- Fixes a number of bugs caused by https://github.com/GTNewHorizons/GTplusplus/pull/767.
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15045
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15045#issuecomment-1847425837
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15045#issuecomment-1847446256

Specifically:
- Fixes incorrect tiers for inputs/outputs/amounts/recipe time for wireless chargers as well as restore missing recipes
- Fixes incorrect tiers for inputs/outputs/amounts/recipe time for overflow valve as well as restore missing recipes
- fix id-shift of transmission components, fix mismatch between internal name and visual item, and restore UHV transmission component to existence while removing the ULV one properly. Also fix the tiers in the gettransmissioncomponent function and thus their tiers in recipes.
- fixed tiers in getFieldGenerator function and thus their tiers in recipes.

I checked in full pack by comparing to 2.4.0 that: the ids are correct now for transmission components, ULV one is properly gone, UHV exists again. wireless charger and overflow valve recipes look the same as 2.4.0 now (and LV one exists).

### CODE REVIEW

File: src/main/java/gtPlusPlus/core/recipe/RECIPES_Machines.java [hunk 1]
```diff
@@ -2715,17 +2715,17 @@ private static void wirelessChargers() {
                 GregtechItemList.Charger_LuV.get(1), GregtechItemList.Charger_ZPM.get(1),
                 GregtechItemList.Charger_UV.get(1), GregtechItemList.Charger_UHV.get(1) };
 
-        for (int tier = 1; tier < aChargers.length; tier++) {
+        for (int tier = 1; tier < aChargers.length + 1; tier++) {
```
Comment (Caedis) [inline src/main/java/gtPlusPlus/core/recipe/RECIPES_Machines.java:2718]: Why not use `<=`?

Comment (chochem) [reply src/main/java/gtPlusPlus/core/recipe/RECIPES_Machines.java:2718]: no particular reason

**Review by Caedis — APPROVED** [review]
