### PR TITLE
Fix duplicate multiblock recipes

### LINKED ISSUE #14405: Four Aqua Regia recipes that are identical in the Multiblock Mixer, but have different Programmed Circuits.
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.4.0RC2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

/

### The Reality

image
image
Exactly the same, but sometimes it can cause it to fail to run

### Your Proposal

Delete the recipe for 2-4 Programmed Circuit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Kyium**
Should fix: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14405 Issue that duplicated an aqua regia recipe. Also removes ~100 duplicate cryogenic freezer recipes.

### CODE REVIEW

File: src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+import net.minecraft.item.ItemStack;
+
+import gnu.trove.map.hash.TCustomHashMap;
+import gnu.trove.set.hash.TCustomHashSet;
+import gregtech.api.util.GT_Recipe;
+import gtPlusPlus.api.objects.Logger;
+
+public class GT_RecipeUtils {
+
+    public static GT_Recipe[] removeDuplicates(GT_Recipe[] inputRecipes, String recipeMapName) {
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java]: Using List instead of array for input/output will remove the need for `toArray` calls

File: src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+        TCustomHashSet<GT_Recipe> recipes = new TCustomHashSet<>(RecipeHashStrat.RecipeHashingStrategy);
+        ArrayList<GT_Recipe> recipeOutput = new ArrayList<>();
+        ArrayList<GT_Recipe> removedRecipes = new ArrayList<>();
+        TCustomHashMap<GT_Recipe, ItemStack> circuitMap = new TCustomHashMap<>(RecipeHashStrat.RecipeHashingStrategy);
+        // create a new input ItemStack array that does not contain programmable circuits if they were in the recipe
+        ArrayList<ItemStack> ItemInputsWithoutProgrammableCircuit = new ArrayList<>();
+        for (GT_Recipe recipeInput : inputRecipes) {
+            ItemStack savedCircuit = null;
+            ItemInputsWithoutProgrammableCircuit.clear();
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java]: Since `ItemInputsWithoutProgrammableCircuit` is cleared on every iteration, why not initialize the variable inside the loop, not outside?

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+            return 0;
+        }
+
+        @Override
+        public boolean equals(GT_Recipe item1, GT_Recipe item2) {
+            return IsRecipeEqual(item1, item2);
+        }
+    };
+
+    public static boolean IsRecipeEqual(GT_Recipe item1, GT_Recipe item2) {
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: `recipe1`, `recipe2`? "item" works as a general term but in MC context it's confusing. Also `areRecipesEqual`

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+    public static final HashingStrategy<GT_Recipe> RecipeHashingStrategy = new HashingStrategy<>() {
+
+        // Not implemented.
+        @Override
+        public int computeHashCode(GT_Recipe stack) {
+            return 0;
+        }
+
+        @Override
+        public boolean equals(GT_Recipe item1, GT_Recipe item2) {
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: same here

File: src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+                    recipeInput.mEUt,
+                    recipeInput.mSpecialValue);
+            if (!recipes.contains(newRecipe)) {
+                // if the recipes customHashSet does not contain the new recipe then add it
+                recipes.add(newRecipe);
+            } else {
+                // add the removed recipe to the removal array with its original item inputs.
+                GT_Recipe recipeCopy = newRecipe.copy();
+                recipeCopy.mInputs = recipeInput.mInputs;
+                removedRecipes.add(recipeCopy);
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java]: Since `removedRecipes` is used only for displaying the amount of reciped recipes, why not use integer counter? Especially recipe copy can be somewhat slow

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+import gregtech.api.util.GT_Recipe;
+
+public class RecipeHashStrat {
+
+    public static final HashingStrategy<GT_Recipe> RecipeHashingStrategy = new HashingStrategy<>() {
+
+        // Not implemented.
+        @Override
+        public int computeHashCode(GT_Recipe stack) {
+            return 0;
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: This means all the objects have the same hashcode, resulting set / map will be basically just a list. Looping recipes to check if it's contained in the map will have its computation time `O(N²)`.
As far as I understand, object hashcode is "allowed" to have collisions. So I made half-baked hashcode implementation: `return Objects.hash(recipe.mDuration, recipe.mEUt);` And this improved performance significantly:
|recipemap|amount of recipes|before|after|
|---|---|---|---|
|centrifuge|1032|1.320 s|197.9 ms|
|mixer|301|186.7 ms|35.45 ms|
|electrolizer|277|81.05 ms|13.65 ms|
|freezer|158|27.11 ms|18.34 ms|

(well it's just one-time run, but you can check it yourself)

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+        ArrayList<String> array2asStrings = new ArrayList<>();
+        for (int i = 0; i < array1.length; i++) {
+            if (array1[i] != null && array2[i] != null) {
+                array1asStrings.add(array1[i].toString());
+                array2asStrings.add(array2[i].toString());
+            } else {
+                return false;
+            }
+        }
+        return array1asStrings.equals(array2asStrings);
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: Why not compare items inside the loop?

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+        ArrayList<String> array2asStrings = new ArrayList<>();
+        for (int i = 0; i < array1.length; i++) {
+            if (array1[i] != null && array2[i] != null) {
+                array1asStrings.add(RecipeHashStrat.createUniqueFluidStackString(array1[i]));
+                array2asStrings.add(RecipeHashStrat.createUniqueFluidStackString(array2[i]));
+            } else {
+                return false;
+            }
+        }
+        return array1asStrings.equals(array2asStrings);
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: Same here

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 9]
```diff
@@ -0,0 +1,110 @@
...
+        return true;
+
+    }
+
+    public static void sortItemStackArray(ItemStack[] itemStackArray) {
+        Arrays.sort(itemStackArray, Comparator.comparing(ItemStack::toString));
+    }
+
+    public static void sortFluidStackArray(FluidStack[] fluidStackArray) {
+        Arrays.sort(fluidStackArray, Comparator.comparing(FluidStack::toString));
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: Since `FluidStack` does not have `toString` implementation, this won't work. Here's my suggestion: `Comparator.comparing(FluidStack::getFluidID).thenComparing(fluidStack -> fluidStack.amount)`

File: src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java [hunk 10]
```diff
@@ -0,0 +1,98 @@
...
+                    }
+                } else {
+                    // If the circuit map does not have the recipe in it yet then add it
+                    circuitMap.put(newRecipe, savedCircuit);
+                }
+            }
+        }
+        // iterate over all recipes without duplicates and add them to the output. If the recipe had a programmable
+        // circuit in it then add it back with its damage value coming from the circuit map.
+        for (GT_Recipe filteredRecipe : recipes.toArray(new GT_Recipe[0])) {
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java]:
```suggestion
        for (GT_Recipe filteredRecipe : recipes) {
```

File: src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java [hunk 11]
```diff
@@ -0,0 +1,98 @@
...
+            // check to see if the recipe is in the circuit map
+            if (circuitMap.contains(filteredRecipe)) {
+                ArrayList<ItemStack> revertedInputItemStackArray = new ArrayList<>(
+                        Arrays.asList(filteredRecipe.mInputs));
+                // add the circuit back
+                revertedInputItemStackArray.add(circuitMap.get(filteredRecipe));
+                // update the item input array with the new input from
+                // ItemInputsWithoutProgrammableCircuit + circuit map circuit
+                filteredRecipe.mInputs = revertedInputItemStackArray.toArray(new ItemStack[0]);
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java]: `ArrayUtils.add` is probably suitable for this task, rather than converting between array <-> list.

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 12]
```diff
@@ -0,0 +1,110 @@
...
+        }
+        if (!areFluidStackArraysEqual(item1.mFluidOutputs, item2.mFluidOutputs)) {
+            return false;
+        }
+        return true;
+
+    }
+
+    public static void sortItemStackArray(ItemStack[] itemStackArray) {
+        Arrays.sort(itemStackArray, Comparator.comparing(ItemStack::toString));
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: Using `toString` for comparing the two seems weird, why not just compare `Item`, damage and stack size?

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 13]
```diff
@@ -0,0 +1,110 @@
...
+    public static boolean areItemsStackArraysEqual(ItemStack[] array1, ItemStack[] array2) {
+        if (array1.length != array2.length) {
+            return false;
+        }
+        ArrayList<String> array1asStrings = new ArrayList<>();
+        ArrayList<String> array2asStrings = new ArrayList<>();
+        for (int i = 0; i < array1.length; i++) {
+            if (array1[i] != null && array2[i] != null) {
+                array1asStrings.add(array1[i].toString());
+                array2asStrings.add(array2[i].toString());
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: Same here

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 14]
```diff
@@ -0,0 +1,110 @@
...
+    public static boolean areFluidStackArraysEqual(FluidStack[] array1, FluidStack[] array2) {
+        if (array1.length != array2.length) {
+            return false;
+        }
+        ArrayList<String> array1asStrings = new ArrayList<>();
+        ArrayList<String> array2asStrings = new ArrayList<>();
+        for (int i = 0; i < array1.length; i++) {
+            if (array1[i] != null && array2[i] != null) {
+                array1asStrings.add(RecipeHashStrat.createUniqueFluidStackString(array1[i]));
+                array2asStrings.add(RecipeHashStrat.createUniqueFluidStackString(array2[i]));
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: Same here

File: src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java [hunk 15]
```diff
@@ -0,0 +1,97 @@
...
+    public static List<GT_Recipe> removeDuplicates(List<GT_Recipe> inputRecipes, String recipeMapName) {
+        TCustomHashSet<GT_Recipe> recipesHashSet = new TCustomHashSet<>(RecipeHashStrat.RecipeHashingStrategy);
+        ArrayList<GT_Recipe> recipeOutput = new ArrayList<>();
+        TCustomHashMap<GT_Recipe, ItemStack> circuitMap = new TCustomHashMap<>(RecipeHashStrat.RecipeHashingStrategy);
+        int removedRecipeCount = 0;
+
+        for (GT_Recipe recipeInput : inputRecipes) {
+            ItemStack savedCircuit = null;
+            // create a new input ItemStack array that does not contain programmable circuits if they were in the recipe
+            ArrayList<ItemStack> ItemInputsWithoutProgrammableCircuit = new ArrayList<>();
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java]: nit: start with lowercase, `itemInputsWithoutProgrammableCircuit`

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 16]
```diff
@@ -0,0 +1,109 @@
...
+            return com.google.common.base.Objects.hashCode(recipe.mDuration, recipe.mEUt);
+        }
+
+        @Override
+        public boolean equals(GT_Recipe recipe1, GT_Recipe recipe2) {
+            return IsRecipeEqual(recipe1, recipe2);
+        }
+    };
+
+    public static boolean IsRecipeEqual(GT_Recipe recipe1, GT_Recipe recipe2) {
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: `areRecipesEqual`

File: src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java [hunk 17]
```diff
@@ -0,0 +1,97 @@
...
+                    recipeInput.mDuration,
+                    recipeInput.mEUt,
+                    recipeInput.mSpecialValue);
+            if (!recipesHashSet.contains(newRecipe)) {
+                // if the recipes customHashSet does not contain the new recipe then add it
+                recipesHashSet.add(newRecipe);
+            } else {
+                // add the removed recipe to the removal array with its original item inputs.
+                GT_Recipe recipeCopy = newRecipe.copy();
+                recipeCopy.mInputs = recipeInput.mInputs;
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/GT_RecipeUtils.java]: These are unneeded now

File: src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java [hunk 18]
```diff
@@ -0,0 +1,109 @@
...
+            return false;
+        }
+        return true;
+
+    }
+
+    public static void sortItemStackArray(ItemStack[] itemStackArray) {
+        Arrays.sort(
+                itemStackArray,
+                Comparator.comparing(ItemStack::getUnlocalizedName).thenComparing(itemStack -> itemStack.stackSize)
```
Comment (miozune) [inline src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: Unlocalized name is not meant for testing equality of items. But I'm not sure what is the good way to compare them... As long as it works it can stay I guess

Comment (miozune) [reply src/main/java/gtPlusPlus/core/util/recipe/RecipeHashStrat.java]: How about this?
```java
Comparator.<ItemStack, Integer>comparing(itemStack -> Item.getIdFromItem(itemStack.getItem()))
        .thenComparing(ItemStack::getItemDamage).thenComparing(itemStack -> itemStack.stackSize));
```

**Review by miozune — APPROVED** [review]
