### PR TITLE
Wireless charger improvements

### LINKED ISSUE #10245: Wireless Charger MK 1 doesn't charge items until world is reloaded, also stops charging after it's chunk is unloaded and reloaded.
### Your GTNH Discord Username

Austin#3823

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Wireless charger (Added by alkalus ID: 1754:890, assuming the rest of them have the same issue) is expected to wirelessly charge items in inventory or being worn (in this case, IC2 electric jetpack).

### The Reality

Wireless charger does NOT charge items in inventory or in armor slots. 

Reloading the world fixes it, but once the chunk it's in is unloaded and reloaded, it's broken again.

### Your Proposal

A world anchor placed nearby will keep it in a working state after the world is reloaded, but it should be fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by minecraft7771**
- The wireless charger is now able to charge tools that use RF power.
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10245

### CODE REVIEW

File: src/main/java/gtPlusPlus/GTplusplus.java [hunk 1]
```diff
@@ -62,6 +63,8 @@
 @Mod(modid = CORE.MODID, name = CORE.name, version = CORE.VERSION, dependencies = "required-after:Forge; after:TConstruct; after:PlayerAPI; after:dreamcraft; after:IC2; after:ihl; after:psychedelicraft; required-after:gregtech; after:Forestry; after:MagicBees; after:CoFHCore; after:Growthcraft; after:Railcraft; after:CompactWindmills; after:ForbiddenMagic; after:MorePlanet; after:PneumaticCraft; after:ExtraUtilities; after:Thaumcraft; after:rftools; after:simplyjetpacks; after:BigReactors; after:EnderIO; after:tectech; after:GTRedtech; after:beyondrealitycore; after:OpenBlocks; after:IC2NuclearControl; after:TGregworks; after:StevesCarts; after:xreliquary;")
 public class GTplusplus implements ActionListener {
 
+	public static boolean hasCOFH = false;
```
Comment (miozune) [inline src/main/java/gtPlusPlus/GTplusplus.java]: There's already a thing `LoadedMods#CoFHCore`

File: src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java [hunk 2]
```diff
@@ -384,6 +388,18 @@ else if ((mitemCurrentCharge + (mVoltageIncrease*5)) <= (mItemMaxCharge - (mVolt
 
 				}
 			}
+			else if (isItemValidRF(mTemp)) {
+				try {
+					IEnergyContainerItem rfItem = (IEnergyContainerItem)mTemp.getItem();
+					long RF = Math.min(rfItem.getMaxEnergyStored(mTemp) - rfItem.getEnergyStored(mTemp), mEntity.getEUVar() * mEUtoRF / 100L);
+					RF = rfItem.receiveEnergy(mTemp, RF > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) RF, false);
+					RF = RF * 100L / mEUtoRF;
```
Comment (miozune) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java]: Rename variable to something different like `usedEU`. Also I think `*100` is not needed here? Also it's magic number.

File: src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java [hunk 3]
```diff
@@ -384,6 +388,18 @@ else if ((mitemCurrentCharge + (mVoltageIncrease*5)) <= (mItemMaxCharge - (mVolt
...
+					mEntity.setEUVar(Math.max(mEntity.getEUVar() - RF, 0));
+					return RF;
```
Comment (miozune) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java]: Don't return, like charging EU does. Also insert `mChargedItems++`, or remove lines below, they're not needed
```
if (mChargedItems < 1){
	return mEuStoredOriginal;
}
```

File: src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java (hunk 2 above)
Comment (minecraft7771) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java]: Afaik the 100 is necessary as the conversion rate is given as 360 instead of 3.6 in Gregtech API. I copied this piece from somewhere else and its the same

Comment (miozune) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/helpers/ChargingHelper.java]: Ah didn't notice, it's fine

**Comment by minecraft7771** [comment]
Changed according to your suggestions, thanks again for your review.

**Comment by Dream-Master** [comment]
@miozune

**Review by miozune — APPROVED** [review]
