### PR TITLE
un-nerf the TGS

### LINKED ISSUE #10561: TGS unintended nerf or tooltip wrong
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-14-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expect it to work as in the tooltip.
image

### The Reality

In reality the modifiers are changed in the latest dev to 1x/2x/3x.

Caused by this PR https://github.com/GTNewHorizons/GTplusplus/pull/206 which has a lot of important fixes too. This looks like an unintended nerf.

Specifically this part: 
image

image

### Your Proposal

Either change the behavior back to 1x/2x/4x OR embrace the unintended nerf and just change the tooltip.

I think such a nerf is well deserved so I would propose to just adjust the tooltip.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by boubou19**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10561

### CODE REVIEW

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntityTreeFarm.java [hunk 1]
```diff
@@ -144,6 +144,23 @@ public boolean isCorrectMachinePart(final ItemStack aStack) {
 		return TreeFarmHelper.isValidForGUI(aStack) && !GT_ModHandler.isElectricItem(aStack) || GT_ModHandler.canUseElectricItem(aStack, 1);
 	}
 
+	/**
+	 * Method used to get the boost based on the ordinal of the saw
+	 * @param sawOrdinal ordinal of the saw
+	 * @return an int corresponding to the boost
+	 */
+	public int getSawBoost(int sawOrdinal){
```
Comment (miozune) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntityTreeFarm.java]: Depending on ordinal can be broken when we add more saw types (and it's a bit hard to read corresponding type), so I'd suggest using enum `SAWTOOL` instead

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntityTreeFarm.java [hunk 2]
```diff
@@ -146,16 +146,16 @@ public boolean isCorrectMachinePart(final ItemStack aStack) {
 
 	/**
 	 * Method used to get the boost based on the ordinal of the saw
-	 * @param sawOrdinal ordinal of the saw
+	 * @param sawType ordinal of the saw
```
Comment (miozune) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntityTreeFarm.java:149]: `type of the saw`

**Review by miozune — APPROVED** [review]
