### PR TITLE
Fix lava->pahoehoe lava recipie

### LINKED ISSUE #12798: GT++ Thermal Boiler never outputs Pahoehoe Lava
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.3.0-RC-2_(MMC)

### Your Server

Singleplayer

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Lava burning in a Thermal Boiler should output Pahoehoe Lava, in addition to other byproducts:

Pahoehoe Lava can then be further processed into other resources, generating a steady if slow stream if infinite lava is supplied to the Boiler.

### The Reality

Lava is consumed, all item outputs and steam are produced, but Pahoehoe lava is not produced.

### Your Proposal

The recipe is correctly defined here: https://github.com/GTNewHorizons/GTplusplus/blob/f9d022bbe6c2c2d30416731cbfa6a14526802fda/src/main/java/gtPlusPlus/core/recipe/RECIPES_GREGTECH.java#L1423

The Thermal Boiler code however only checks for solid outputs of the recipe, it never even looks at the fluid outputs when lava is the input: https://github.com/GTNewHorizons/GTplusplus/blob/f9d022bbe6c2c2d30416731cbfa6a14526802fda/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java#L103

Using Solar Salt properly checks and generates fluid outputs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by posiaden123**
Fixes GTNewHorizons/GT-New-Horizons-Modpack#12798

### CODE REVIEW

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java [hunk 1]
```diff
@@ -143,6 +143,11 @@ public boolean checkRecipe(ItemStack aStack) {
                                 this.mOutputItems = new ItemStack[] { GT_Utility.copy(tRecipe.getOutput(5)) };
                             }
                         }
+                        if (tRecipe.mFluidOutputs.length != 0) {
+                            for (FluidStack aOutput : tRecipe.mFluidOutputs) {
+                                this.addOutput(FluidUtils.getFluidStack(aOutput, aOutput.amount));
```
Comment (kuba6000) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java]: You should use this.mOutputFluids for recipe outputs

**Review by kuba6000 — CHANGES_REQUESTED** [review]

**Comment by Dream-Master** [comment]
@posiaden123

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java [hunk 2]
```diff
@@ -143,6 +143,12 @@ public boolean checkRecipe(ItemStack aStack) {
                                 this.mOutputItems = new ItemStack[] { GT_Utility.copy(tRecipe.getOutput(5)) };
                             }
                         }
+                        if (tRecipe.mFluidOutputs.length != 0) {
+                            for (FluidStack aOutput : tRecipe.mFluidOutputs) {
+                                this.mOutputFluids = new FluidStack[] {
+                                        FluidUtils.getFluidStack(aOutput, aOutput.amount) };
+                            }
```
Comment (kuba6000) [inline src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java]: Now if there is a recipe with more than 1 fluid output it will only output the last one, you should initialize the array before the loop and add outputs inside it
```suggestion
                            final FluidStack[] mFluidOutputs = tRecipe.mFluidOutputs;
                            this.mOutputFluids = new FluidStack[mFluidOutputs.length];
                            for (int i = 0, mFluidOutputsLength = mFluidOutputs.length; i < mFluidOutputsLength; i++) {
                                this.mOutputFluids[i] = mFluidOutputs[i].copy();
                            }
```

**Review by kuba6000 — CHANGES_REQUESTED** [review]

File: src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java (hunk 2 above)
Comment (posiaden123) [reply src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java]: I see what you mean now. I was trying to find examples in the rest of the mod but couldn't.

**Review by kuba6000 — APPROVED** [review]
